config/routes.rb
Rails.application.routes.draw do
  post '/contact', to: 'welcome#contact'
  get '/portfolio', to: 'welcome#portfolio'
  root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
require 'slack-notifier'

class WelcomeController < ApplicationController
  def show
  end

  def index
  end

  def portfolio
  end

  def contact
    unless [:name, :email, :message].all? {|s| params[s].present? }
      return render json: { error: 'Please fill up all fields.' }, status: :unprocessable_entity
    end

    return render json: { error: 'No slack endpoint set!' }, status: :unprocessable_entity unless ENV['SLACK_WEBHOOK_URL']

    notifier = Slack::Notifier.new(ENV['SLACK_WEBHOOK_URL'],
                                   channel: '#general',
                                   username: 'contact-bot')

    msg = notifier.escape(params[:message])
    name = notifier.escape(params[:name])
    email = notifier.escape(params[:email])
    href = mail_to(params[:email],
                   subject: 'Hello from Conjur!',
                   cc: 'tech@conjur.tech',
                   body: "Hi there,\n\nWe've received your message and..\n\n\n\nRegards,\n\nConjur Technologies\n\n\n\n---\n\nOriginal Message:\n\n#{msg}"
    )

    payload = {
        fallback: format("New message from #{name} (#{email}) received - #{msg}"),
        pretext: "*Message Details*",
        color: "#9ad3de",
        fields: [
            {
                title: 'Name',
                value: name,
                short: true
            },
            {
                title: 'Email',
                value: format("[#{email}](#{href})"),
                short: true
            },
            {
                title: 'Message',
                value: msg,
                short: false
            },
            {
                value: format("[Reply to #{name}](#{href})"),
                short: false
            }
        ],
        mrkdwn_in: ["pretext", "fields"] # fields doesn't work, have to use format method still
    }

    notifier.ping format('<!channel>: Great News! New lead received through [conjur.tech](http://conjur.tech):'), attachments: [payload]

    render json: { message: 'ok' }
  end

  private

  def format(msg)
    Slack::Notifier::LinkFormatter.format(msg)
  end

  def mail_to(email_address, options = {})
    options = options.stringify_keys
    extras = %w{ cc bcc body subject }.map! { |item|
      option = options.delete(item) || next
      "#{item}=#{Rack::Utils.escape_path(option)}"
    }.compact
    extras = extras.empty? ? '' : '?' + extras.join('&')

    "mailto:#{email_address}#{extras}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <%= image_tag("conjur_logo.png", :class => "img-responsive") %>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about-us">About</a></li>
        <li><a href="#contact-us">Contact</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conjur Technologies</title>
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,300italic,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- See: https://github.com/jlmakes/scrollReveal.js/wiki/Tips#making-sure-your-elements-load-hidden -->
  <style>[data-sr] { visibility: hidden; }</style>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-70608575-1', 'auto');
      ga('send', 'pageview');
  </script>
  <!--Start of Zopim Live Chat Script-->
  <script type="text/javascript">
    window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
        d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
    _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
      $.src="//v2.zopim.com/?3m21xMW9DQyFghuEJ4VMGMY4EHaYRpMB";z.t=+new Date;$.
          type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
  </script>
  <!--End of Zopim Live Chat Script-->
</head>
<body data-spy="scroll" data-target="#navbar-conjur" data-offset="0">

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="navbar-conjur">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-conjur-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag 'logo_conjur.png', alt: 'Conjur' %></a> <!-- adjusted_text-small variant -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-conjur-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a class="smoothscroll" href="#process">About</a></li>
        <li><a class="smoothscroll" href="#portfolio">Our Works</a></li>
        <li><a class="smoothscroll" href="#team">Our Team</a></li>
        <li><a class="smoothscroll" href="#contact">Contact</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="jumbotron" id="home-jumbotron">
  <div class="jumbotron-contents">
    <h1>On-Demand Software Development</h1>
    <p>
      <span data-sr="enter bottom, hustle 40px, over 0.6s">The <strong>Software</strong> you Like .</span>
      <span data-sr="enter bottom, hustle 40px, over 0.6s, wait 0.5s">The <strong>Technology</strong> you Deserve .</span>
      <span data-sr="enter bottom, hustle 40px, over 0.6s, wait 1.0s">The <strong>Automation</strong> you Need </span>
    </p>
    <p><a class="btn btn-lg btn-clear smoothscroll" href="#process" role="button">Learn more</a></p>
  </div>
</div>

<div class="container" id="process">
  <div class="row" id="process-section">
    <div class="process-step" data-sr="enter left, hustle 70px">
      <div class="process-image">
        <%= image_tag('icon_consult.png') %>
      </div>
      <div class="process-text">
        <h2>Consult Us</h2>
      </div>
    </div>
    <div class="process-step" data-sr="wait 0.5s, enter left, hustle 70px">
      <div class="process-image with-line">
        <%= image_tag('icon_develop.png') %>
      </div>
      <div class="process-text">
        <h2>We Develop</h2>
      </div>
    </div>
    <div class="process-step" data-sr="wait 1.0s, enter left, hustle 70px">
      <div class="process-image with-line">
        <%= image_tag('icon_results.png') %>
      </div>
      <div class="process-text">
        <h2>Get Results</h2>
      </div>
    </div>
  </div>
</div>

<div id="upgrade-cta-section">
  <div class="container-fluid">
    <h1>Upgrade Your Business Now</h1>
    <p>Stop using outdated solutions or paper based methods today!</p>
  </div>
</div>

<div id="featurette-section">
  <div class="featurette primary">
    <div class="container">
      <div class="row">
        <div class="featurette-image" data-sr="scale up 50%">
          <%= image_tag 'icon_automate.png' %>
        </div>
        <div class="featurette-text" data-sr="enter bottom, hustle 50px">
          <h1>Automate Your Process</h1>
          <p class="lead">Software that runs your business</p>
          <p>
            Whether the task be menial or critical, automating all
            or a portion of your business process means gained
            efficiencies. That means <strong>BIG</strong> financial savings!
          </p>
          <p>
            Eliminate bottlenecks and free your workforce so they can spend
            more time concentrating on taking your company to the next level.
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="featurette alternate">
    <div class="container">
      <div class="row">
        <div class="featurette-image" data-sr="enter left, hustle 50px, over 1.2s">
          <%= image_tag 'icon_integrate.png' %>
        </div>
        <div class="featurette-text" data-sr="enter right, hustle 50px, over 1.2s">
          <h1>Integrated Solutions</h1>
          <p class="lead">See for yourself</p>
          <p>
            We can help you create almost any sort of customized software you can think of,
            from <strong>CRM & HRM systems</strong> to <strong>e-commerce platforms</strong>.
          </p>
          <p>
            Transform your business from a paper based system and harness your new
            digitally powered productivity, or prototype and create your
            new web application with us.
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="featurette primary">
    <div class="container">
      <div class="row">
        <div class="featurette-image with-perspective" data-sr="spin 90deg, over 1.2s">
          <%= image_tag 'icon_responsive.png' %>
        </div>
        <div class="featurette-text" data-sr="enter top, hustle 50px, over 1.2s">
          <h1>Fully Responsive Webapps</h1>
          <p class="lead">From desktop to mobile</p>
          <p>
            We believe in building webapps that can be used
            in any screen size, from your laptop to your favourite
            smart phone.
          </p>
          <p>
            Ensure your site has top-notch <strong>SEO</strong> with mobile optimized
            applications, superb loading speeds and industry best practices from day one with us.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="portfolio-section">
  <div class="container text-center" id="portfolio">
    <h1>Our Works</h1>
    <div class="grid">
      <figure class="effect-zoe">
        <%= link_to 'https://payboy.biz', target: '_blank' do %>
            <%= image_tag 'portfolio_payboy.png', class: 'center-block', alt: 'Payboy' %>
        <% end %>
        <figcaption>
          <h2>Payboy</h2>
          <p>Human Resource <br> Management System</p>
          <%= link_to 'Payroll Software Singapore', 'https://payboy.biz', target: '_blank' %>
        </figcaption>
      </figure>
      <figure class="effect-zoe">
        <%= link_to 'https://shoheuken.com', target: '_blank' do %>
            <%= image_tag 'tuition_notifications.png', class: 'center-block', alt: 'Shoheuken' %>
        <% end %>
        <figcaption>
          <h2>Shoheuken.com</h2>
          <p>Quiz / School Management System</p>
          <%= link_to 'View more', 'https://shoheuken.com', target: '_blank' %>
        </figcaption>
      </figure>
      <figure class="effect-zoe">
        <%= link_to 'https://www.skylinetransports.com', target: '_blank' do %>
            <%= image_tag 'portfolio_skyline.png', class: 'center-block', alt: 'Skyline Transports' %>
        <% end %>
        <figcaption>
          <h2>Skyline Transp</h2>
          <p>Limousine <br> Booking System</p>
          <%= link_to 'View more', 'https://www.skylinetransports.com', target: '_blank' %>
        </figcaption>
      </figure>
      <figure class="effect-zoe">
        <%= link_to 'https://www.transcendtransports.com', target: '_blank' do %>
            <%= image_tag 'portfolio_transcend.png', class: 'center-block', alt: 'Transcend Transports' %>
        <% end %>
        <figcaption>
          <h2>Transcend Trans</h2>
          <p>Limousine <br> Booking System</p>
          <%= link_to 'View more', 'https://www.transcendtransports.com', target: '_blank' %>
        </figcaption>
      </figure>
      <figure class="effect-zoe">
        <%= link_to 'https://danityroses.com', target: '_blank' do %>
            <%= image_tag 'portfolio_danityroses.png', class: 'center-block', alt: 'Danity Roses' %>
        <% end %>
        <figcaption>
          <h2>Danity Roses</h2>
          <p>Blogshop</p>
          <%= link_to 'View more', 'https://danityroses.com', target: '_blank' %>
        </figcaption>
      </figure>
      <figure class="effect-zoe">
        <%= link_to 'https://therideidentity.com', target: '_blank' do %>
            <%= image_tag 'portfolio_therideidentity.png', class: 'center-block', alt: 'The Ride Identity' %>
        <% end %>
        <figcaption>
          <h2>The Ride Identity</h2>
          <p>Blogshop</p>
          <%= link_to 'View more', 'https://therideidentity.com', target: '_blank' %>
        </figcaption>
      </figure>
    </div>
  </div>
</div>

<div id="about-us-section">
  <div class="container text-center" id="team">
    <h1>Our Team</h1>
    <div class="row">
      <div class="col-xs-12 col-lg-3">
        <%= image_tag 'profile_henry.png', class: 'img-responsive img-circle center-block' %>
        <p class="team-member-name">Henry Chua</p>
        <p class="team-member-role">Frontend Engineer</p>
        <p class="team-member-quote">Vue.js, React, React Native</p>
      </div>
      <div class="col-xs-12 col-lg-3">
        <%= image_tag 'profile_ivan.png', class: 'img-responsive img-circle center-block' %>
        <p class="team-member-name">Ivan Poon</p>
        <p class="team-member-role">Software Architect</p>
        <p class="team-member-quote">Cloud Infrastructure, Blockchain Development</p>
      </div>
      <div class="col-xs-12 col-lg-3">
        <%= image_tag 'profile_terence.png', class: 'img-responsive img-circle center-block' %>
        <p class="team-member-name">Terence Toh</p>
        <p class="team-member-role">Business Development</p>
        <p class="team-member-quote">Business Development, Operations, HR</p>
      </div>
      <div class="col-xs-12 col-lg-3">
        <%= image_tag 'profile_pingchiang.png', class: 'img-responsive img-circle center-block' %>
        <p class="team-member-name">Sng Ping Chiang</p>
        <p class="team-member-role">Backend Engineer</p>
        <p class="team-member-quote">Ruby on Rails, Tensorflow</p>
      </div>
      <div class="col-xs-12 col-lg-3">
        <%= image_tag 'profile_jack.png', class: 'img-responsive img-circle center-block' %>
        <p class="team-member-name">Jack Yeu</p>
        <p class="team-member-role">Designer</p>
        <p class="team-member-quote">UI/UX, Graphic Design, Vue.js, React</p>
      </div>
    </div>
  </div>
</div>

<div id="contact-us-section">
  <div class="container text-center" id="contact">
    <h1>Get In Touch</h1>
    <%= form_tag '/contact', remote: true, id: 'contact_form' do %>
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <input name="name" type="text" class="form-control" id="name-input" placeholder="Name" required>
        </div>
        <div class="col-xs-12 col-md-6">
          <input name="email" type="email" class="form-control" id="email-input" placeholder="Email">
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <textarea name="message" class="form-control" id="message-input" rows="6"
                    placeholder="Leave us a message and we'll get back to you within one working day." required></textarea>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <button type="submit" class="btn btn-lg btn-primary btn-send pull-right">SEND</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/portfolio.html.erb
<div id="portfolio-page">
  <div id="portfolio-nav">
    <div id="portfolio-nav-header">
      <%= image_tag 'logo_conjur.png', alt: 'Conjur' %>
      <p>Projects</p>
      <%= link_to '< Back to home', root_path %>
    </div>
    <ul>
      <li>
        <%= link_to portfolio_path do %>
            <%= image_tag 'tuition_notifications.png', class: 'img-responsive center-block', alt: 'Shoheuken' %>
        <% end %>
      </li>
      <li>
        <%= link_to portfolio_path do %>
            <%= image_tag 'tuition_notifications.png', class: 'img-responsive center-block', alt: 'Shoheuken' %>
        <% end %>
      </li>
    </ul>
  </div>

  <div id="portfolio-content" class="text-center" id="team">
    <div id="portfolio-slider">
      <div>
        <%= image_tag 'tuition_notifications.png', class: 'img-responsive center-block', alt: 'Shoheuken' %>
      </div>
      <div>
        <%= image_tag 'tuition_calendar.png', class: 'img-responsive center-block', alt: 'Shoheuken' %>
      </div>
      <div>
        <%= image_tag 'tuition_quiz.png', class: 'img-responsive center-block', alt: 'Shoheuken' %>
      </div>
      <div>
        <%= image_tag 'tuition_side_bar.png', class: 'img-responsive center-block', alt: 'Shoheuken' %>
      </div>
      <div>
        <%= image_tag 'tuition_statistics.png', class: 'img-responsive center-block', alt: 'Shoheuken' %>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Quiz System / Class Attendance</h1>
          <p><a href="www.shoheuken.com">www.shoheuken.com</a></p>
          <p>A full featured system for a small tuition centre business</p>
          <p>Features:</p>
          <ul>
            <li>Random Quiz Generation</li>
            <li>Auto Mark System</li>
            <li>Student Results Statistics</li>
            <li>Attendance Tracking</li>
            <li>Automatic Payment Calculation based on sessions attended</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>